[package]
name = "rp2040_temp_fan_ctrl"
version = "0.2.0"
edition = "2024"
homepage = "https://github.com/jepomeroy/rp2040_temp_fan_ctrl"
description = "A Rust Embassy impl for the rp2040 microcontroller monitoring average temps and controlling fans"
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
features = ["rt", "rom-v2-intrinsics", "defmt", "rtic-monotonic"]
targets = ["thumbv6m-none-eabi"]

[dependencies]
embassy-embedded-hal = { version = "0.6.0", features = ["defmt"] }
embassy-executor = { version = "0.10.0", features = [
    "platform-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "defmt",
] }
embassy-rp = { version = "0.10.0", features = ["defmt", "rp2040", "time-driver"] }
embassy-usb = { version = "0.6.0", features = ["defmt"] }

cortex-m = { version = "0.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7"
defmt = "1.0.1"
defmt-rtt = "1.0.0"
panic-probe = { version = "0.3", features = ["print-defmt"] }
static_cell = "2.1.1"
portable-atomic = { version = "1", features = ["critical-section"] }
embassy-time = "0.5.1"
embassy-time-driver = "0.2.2"
